# Generated by Django 2.0.2 on 2018-03-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=1024)),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTriple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=1024)),
                ('text', models.CharField(max_length=1024)),
                ('relation', models.CharField(default='', max_length=1024)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='DecomposedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('pos_tagging', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='GoldAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity1', models.CharField(default='', max_length=1024)),
                ('relation', models.CharField(default='', max_length=1024)),
                ('entity2', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='PredAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='QueryCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=1024)),
                ('e1', models.CharField(default='', max_length=1024)),
                ('e2', models.CharField(default='', max_length=1024)),
                ('r1', models.CharField(default='', max_length=1024)),
                ('r2', models.CharField(default='', max_length=1024)),
                ('r3', models.CharField(default='', max_length=1024)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('answer_type', models.CharField(default='Other', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Tripple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(default='', max_length=1024)),
                ('subject_text', models.CharField(default='', max_length=1024)),
                ('subject_id', models.CharField(default='', max_length=1024)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripples', to='web.Question')),
            ],
        ),
        migrations.AddField(
            model_name='querycandidate',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_candidates', to='web.Question'),
        ),
        migrations.AddField(
            model_name='predanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pred_answers', to='web.Question'),
        ),
        migrations.AddField(
            model_name='graphedge',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_edges', to='web.Question'),
        ),
        migrations.AddField(
            model_name='goldanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_answers', to='web.Question'),
        ),
        migrations.AddField(
            model_name='decomposedquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decomposed_list', to='web.Question'),
        ),
        migrations.AddField(
            model_name='answertriple',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_triples', to='web.Question'),
        ),
        migrations.AddField(
            model_name='answercandidate',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='web.Question'),
        ),
    ]
